!/bin/bash

# degrees in C
THERMAL_ALERT=75

DISCORD_SERVER_NAME="<YOUR SERVER>"

DISCORD_GENERAL_HOOK="<WEBHOOK_URL_HERE>"

DISCORD_THERMAL_HOOK="<WEBHOOK_URL_HERE>"

DISCORD_STORAGE_HOOK="<WEBHOOK_URL_HERE>"

