!/bin/bash

# degrees in C
THERMAL_ALERT=75

STORAGE_MONITOR=("/")

# must declare associated array explicitly
declare -A STORAGE_ALERT
# storage in GiB
STORAGE_ALERT=(["/"]=5)

SERVER_DOMAIN="localhost"

DISCORD_SERVER_NAME="<YOUR SERVER>"

DISCORD_GENERAL_HOOK="<WEBHOOK_URL_HERE>"

DISCORD_THERMAL_HOOK="<WEBHOOK_URL_HERE>"

DISCORD_STORAGE_HOOK="<WEBHOOK_URL_HERE>"

